chat/urls.py
""" soMedia URL Configuration """

from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.home, name='home'),
    path('posts/add', views.add_post, name='add_post'),
    path('comments/add/<post_id>', views.add_comment, name='add_comment')
]

chat/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
	""" The Posts Models """

	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', on_delete=models.CASCADE)
	picture = models.ImageField(upload_to='posts', blank=True)
	text = models.TextField(max_length=2048, blank=True)
	posted_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.user.username}'s post"

class Comment(models.Model):
	""" The comments Models """

	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments', on_delete=models.CASCADE)
	post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
	text = models.TextField(max_length=2048, blank=True)
	comment_date = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
	""" Form for handling addition of posts """

	class Meta:
		model = Post
		fields = ('picture', 'text')


class CommentForm(forms.Form):
	""" Form for adding comments"""

	text = forms.CharField(label="Comment", widget=forms.Textarea(attrs={'rows': 3}))

	def save(self, post, user):
		""" custom save method to create comment """

		comment = Comment.objects.create(text=self.cleaned_data.get('text', None), post=post, user=user)

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST

from .forms import CommentForm, PostForm
from .models import Post


@login_required
def home(request):
	""" The home news feed page """

	# Get users whose posts to display on news feed and add users account
	_users = list(request.user.followers.all())
	_users.append(request.user)

	# Get posts from users accounts whose posts to display and order by latest
	posts = Post.objects.filter(user__in=_users).order_by('-posted_date')
	comment_form = CommentForm()
	return render(request, 'chat/home.html', {'posts': posts, 'comment_form': comment_form})


@login_required
def add_post(request):
	""" create a new posts to user """
	# handle only POSTed Data
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		# validate form based on form definition
		if form.is_valid():
			post = form.save(commit=False)
			# add the post user to the existing form
			# this method can be declared in the postForm easily by overiding the save() method
			# and adding user before saving.
			# See implementation of CommentForm
			post.user = request.user
			post.save()
			return redirect('chat:home')
	else:
		form = PostForm()
	return render(request, 'chat/add_post.html', {'form': form})


@login_required
@require_POST
def add_comment(request, post_id):
	""" Add a comment to a post """

	form = CommentForm(request.POST)
	if form.is_valid():
		# pass the post id to the comment save() method which was overriden
		# in the CommentForm implementation
		comment = form.save(Post.objects.get(id=post_id), request.user)
	return redirect(reverse('chat:home'))

chat/templates/chat/add_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
	New Post
{% endblock %}

{% block content %}
	<div class="container-fluid row">
		<div class="col-md-8">
			<h1 class="py-3 px-2 bg-dark text-light d-flex justify-content-between">New Post </h1>
			<div class=" bg-grey container mx-auto py-3">

				{% if form.non_field_errors %}
		          <div class="alert alert-warning alert-dismissible fade show" style="font-size: 11px" role="alert">
		            {{ form.non_field_errors }}
		            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		              <span aria-hidden="true">&times;</span>
		            </button>
		          </div>
		        {% endif %}

		        <form method="POST" enctype="multipart/form-data">
		          {% csrf_token %}
		          {% for field in form %}
		          <div class="form-group">
		            {% if field.errors %}
		              <div class="alert alert-warningalert-dismissible fade show" role='alert'>
		                {{ field.errors }}
		                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		                  <span aria-hidden="true">&times;</span>
		                </button>
		              </div>
		            {% endif %}

		            {{ field.label_tag }}
		            {{ field|add_class:'form-control' }}
		          </div>
		          {% endfor %}
		          <input type='submit' class="btn btn-primary btn-block" value='submit'>
		        </form>
			</div>
		</div>
		<div class="col-md-4">
			<h3 class="py-3 px-2 bg-dark text-light text-right">Me</h3>
			{% include 'accounts/profile.html' %}
		</div>
	</div>
{% endblock %}

chat/templates/chat/home.html
{% extends 'base.html' %}

{% load widget_tweaks %}


{% block title %}
	Feeds
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-8 col-sm-12">
			<h1 class="py-3 px-2 bg-dark text-light d-flex justify-content-between">News Feed <a href="{% url 'chat:add_post' %}"><i class="fas fa-plus text-light"></i></a></h1>
			<div class="container bg-grey">
				{% for post in posts %}
					<div class=" my-4 card" style="box-shadow: #484646 0px 4px 1px">
						{% if post.picture %}
							<div class="card-img-top text-center">
								<img style="max-width: 99%; height: auto;" src="{{ post.picture.url }}">
							</div>
						{% endif %}
						<div class="card-body">
							<div class="card-title text-right">
								{% if post.user == request.user %}
									<strong>Me</strong>
								{% else %}
								<strong>
									<a class='text-dark' href="{% url 'accounts:view-profile' post.user.username %}">{{ post.user.first_name }} {{ post.user.last_name }}</a>
								</strong>
								{% endif %}
							</div>
							<div class="card-text">
								{{ post.text }}
							</div>
						</div>
						<div class="card-footer">
							<div class="d-flex justify-content-between">
								<i>{{ post.posted_date }}</i>
								<a class="btn btn-outline-dark" data-toggle='collapse' href="#comments{{ post.id }}" role="button"  aria-expanded="false" aria-controls="comments{{ post.id }}">
									<i class="fas fa-2x fa-comment"></i> <span class="badge badge-danger">{{ post.comments.count }}</span>
								</a>
							</div>
							<div class="collapse" id="comments{{ post.id }}">
								<div class="mt-2 card card-body">
									{% for comment in post.comments.all %}
										<code class="blockquote text-center border-bottom" style="font-size: 0.8rem">
											{{ comment.text }}

											<footer class="blockquote-footer">
											{% if comment.user == user %}
												Me
											{% else %}
												{{ comment.user.first_name }} {{ comment.user.last_name }}
											{% endif %}
												{{ comment.comment_date}}
											</footer>
										</code>
									{% endfor %}
									<form method="POST" action="{% url 'chat:add_comment' post.id %}">
										{% csrf_token %}
										{% for field in comment_form %}
											<div class="form-group">
									            {% if field.errors %}
									              <div class="alert alert-warningalert-dismissible fade show" role='alert'>
									                {{ field.errors }}
									                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
									                  <span aria-hidden="true">&times;</span>
									                </button>
									              </div>
									            {% endif %}

									            {{ field.label_tag }}
									            {{ field|add_class:'form-control' }}
									        </div>
									    {% endfor %}
										<input type="submit" value="post" class="btn btn-outline-primary">
									</form>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
		<div class="col-md-4">
			<h3 class="py-3 px-2 bg-dark text-light text-right">Me</h3>
			{% include 'accounts/profile.html' %}
		</div>
	</div>
{% endblock %}