accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'
urlpatterns = [
	path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('followers/', views.followers, name='followers'),
    path('my-profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<username>/', views.profile, name='view-profile'),
    path('users/follow/<username>/', views.follow, name='follow'),
    path('users/unfollow/<username>/', views.unfollow, name='unfollow'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    """ Custom User Model
        In cases where we just want to add a new field to the already existing user, subclass
        the `AbstractUser` and add the required fields
        Ensure to update the `settings.AUTH_USER_MODEL` value
    """
    followers = models.ManyToManyField("self", blank=True)

    def is_following(self, user):
        return user in self.followers.all()


class UserProfile(models.Model):
    """ Profile data of user """

    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='profile',
                                verbose_name='other Details')
    picture = models.ImageField(upload_to='profile_pictures', blank=True, null=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    phone = models.CharField(max_length=11, blank=True)
    address = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    """ Create a profile anytime a new user is created """
    if kwargs['created']:
        user_profile = UserProfile.objects.get_or_create(
            user=kwargs['instance']
        )

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms.models import inlineformset_factory

from .models import UserProfile

User = get_user_model()


class RegistrationForm(UserCreationForm):
    """ Extending the UserCreationForm to specify custom rendering """

    email = forms.EmailField(required=True)
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput,
                                required=True,
                                )
    password2 = forms.CharField(label='Confirm Password',
                                widget=forms.PasswordInput,
                                required=True,
                                )
    username = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('first_name',
                  'last_name',
                  'username',
                  'email',
                  'password1',
                  'password2',
                  )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture', 'bio', 'phone', 'website', 'address')

accounts/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import ProfileForm, RegistrationForm
from .models import UserProfile

User = get_user_model()


def register(request):
    """ Add a new user """
    # redirect if user is already loggedIn
    if request.user.is_authenticated:
        return redirect(reverse('chat:home'))

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        # Process POSTed Form data
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(username=request.POST['username'],
                                    password=request.POST['password1']
                                    )
            # authenticate and log user in, then redirect to newsFeeds
            login(request, new_user)
            return redirect(reverse('chat:home'))

    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def profile(request, username):
    """ view profile of user with username """

    user = User.objects.get(username=username)
    # check if current_user is already following the user
    is_following = request.user.is_following(user)
    return render(request, 'accounts/users_profile.html', {'user': user, 'is_following': is_following})


@login_required
def edit_profile(request):
    """ edit profile of user """

    if request.method == "POST":
        # instance kwargs passed in sets the user on the modelForm
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view-profile', args=(request.user.username,)))
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit_profile.html', {'form': form})


@login_required
def followers(request):
    """ Return the lists of friends user is  following and not """

    # get users followed by the current_user
    users_followed = request.user.followers.all()

    # get_users not followed and exclude current_user from the list
    unfollowed_users = User.objects.exclude(id__in=users_followed).exclude(id=request.user.id)
    return render(request, 'accounts/followers.html',
                  {'users_followed': users_followed, 'unfollowed_users': unfollowed_users})


@login_required
def follow(request, username):
    """ Add user with username to current user's following list """

    request.user.followers.add(User.objects.get(username=username))
    return redirect('accounts:followers')


def unfollow(request, username):
    """ Remove username from user's following list """

    request.user.followers.remove(User.objects.get(username=username))
    return redirect('accounts:followers')

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
	Edit Profile
{% endblock %}

{% block content %}
	<div class="container col-md-8">
		<div class="card">
			{% if user.profile.picture %}
				<img class="card-img-top" src='{{ user.profile.picture.url }}'>
			{% else %}
				<div class="container mt-1 text-center"><i class="fas fa-9x fa-user"></i></div>
			{% endif %}

		<div class="card-body">
			<div class="card-title">
				{{ user.first_name }} {{ user.last_name }}
			</div>
		</div>
		<div class="card-footer">
			{% if formset.non_field_errors %}
        <div class="alert alert-warning alert-dismissible fade show" style="font-size: 11px" role="alert">
          {{ formset.non_field_errors }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}

      <form method="POST" enctype="multipart/form-data">

				{% csrf_token %}

				{% for field in form %}
					<div class="form-group">
						{% if field.errors %}
							<div class="alert alert-warningalert-dismissible fade show" role='alert'>
								{{ field.errors }}
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endif %}

						{{ field.label_tag }}
						{{ field|add_class:'form-control' }}
					</div>
				{% endfor %}
	      <input type="submit" value="Update Profile" class="btn btn-primary btn-block">
	    </form>
		</div>
	</div>

	</div>
{% endblock %}

accounts/templates/accounts/followers.html
{% extends 'base.html' %}

{% block title %}
	Feeds
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col"></div>
		<div class="col-md-10">
			<h1 class="py-3 px-2 bg-dark text-light">Following</h1>
			<div class="container">
				{% for user in users_followed %}
					<div class="my-4 border-top py-2">
						<div class="row">
							<div class="col-md-2 text-center">
								{% if user.profile.picture %}
									<img class="card-img-top" style="max-height: 30%; max-width: 40%; border-radius: 50%" src='{{ user.profile.picture.url }}'>
									{% else %}
										<div class="container mt-1 text-center"><i class="fas fa-5x fa-user"></i></div>
								{% endif %}
							</div>
							<div class="col-md-10">
								<div class="h-100 w-100 d-flex align-items-center justify-items-center">
									<a href="{% url 'accounts:view-profile' user.username %}">{{ user.first_name }} {{ user.last_name }} </a>
									 <a class="mx-2 btn btn-light" href="{% url 'accounts:unfollow' user.username %}"> Unfollow <i class="fas fa-user-cogs"></i></a>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			<h3 class="py-3 px-2 bg-dark text-light">Follow Friends</h3>
				<div class="container">
					{% for user in unfollowed_users %}
						<div class="my-4 border-top py-2">
							<div class="row">
								<div class="col-md-2 text-center">
									{% if user.profile.picture %}
										<img class="card-img-top" style="max-height: 30%; max-width: 40%; border-radius: 50%" src='{{ user.profile.picture.url }}'>
										{% else %}
											<div class="container mt-1 text-center"><i class="fas fa-5x fa-user"></i></div>
									{% endif %}
								</div>
								<div class="col-md-10">
									<div class="h-100 w-100 d-flex align-items-center justify-items-center">
											<a href="{% url 'accounts:view-profile' user.username %}">{{ user.first_name }} {{ user.last_name }} </a>
										<a class="btn btn-dark mx-3" href="{% url 'accounts:follow' user.username %}"><i class="fas fa-user-plus"></i></a>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
		</div>
	</div>
{% endblock %}

accounts/templates/accounts/profile.html
<div class="card">
	{% if user.profile.picture %}
		<img class="card-img-top" src='{{ user.profile.picture.url }}'>
	{% else %}
		<div class="container mt-1 text-center"><i class="fas fa-9x fa-user"></i></div>
	{% endif %}
	<div class="card-body">
		<div class="card-title">
			{{ user.first_name }} {{ user.last_name }}
		</div>
		<div class="card-text">
			{{ user.profile.bio }}
		</div>
	</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item"><strong><i class="fa fa-fw fa-user-alt"></i></strong> {{ user.username }}</li>
		<li class="list-group-item"><strong><i class="fa fa-fw fa-envelope"></i></strong> {{ user.email }}</li>
		<li class="list-group-item"><strong><i class="fa fa-fw fa-phone"></i></strong> {{ user.profile.phone }}</li>
		<li class="list-group-item"><strong><i class="fa fa-fw fa-globe"></i></strong> {{ user.profile.website }}</li>
		<li class="list-group-item"><strong><i class="fa fa-fw fa-map-marker-alt"></i></strong> {{ user.profile.address }}</li>
	</ul>
	{% if request.user == user %}
		<div class="card-body">
			<a href="{% url 'accounts:edit_profile' %}" class="card-link btn btn-danger">Edit Profile</a>
		</div>
	{% endif %}
</div>

accounts/templates/accounts/users_profile.html
{% extends 'base.html' %}

{% block title %}
	{% if request.user == user %}
		My Profile
	{% else %}
		{{ user.username }}'s Profile
	{% endif %}
{% endblock %}

{% block content %}
	<div class="container col-md-8">
		{% include 'accounts/profile.html' %}
	</div>
{% endblock %}